# Generated by Django 3.2.4 on 2021-06-17 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTask',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
                ('task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasks.task')),
            ],
            options={
                'verbose_name': 'Project Task',
                'verbose_name_plural': 'Project Tasks',
                'db_table': 'project_task_mapping',
                'unique_together': {('project', 'task')},
            },
        ),
        migrations.AddField(
            model_name='project',
            name='tasks',
            field=models.ManyToManyField(through='projects.ProjectTask', to='tasks.Task'),
        ),
    ]
