# Generated by Django 3.2.4 on 2021-06-17 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20210617_1447'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='tasks',
        ),
        migrations.AddField(
            model_name='project',
            name='duration',
            field=models.PositiveIntegerField(db_index=True, default=0),
        ),
        migrations.DeleteModel(
            name='ProjectTask',
        ),
    ]
